apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k3s-app.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "k3s-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "k3s-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k3s-app.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.rbac.createServiceAccount }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.security.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image.repository }}:{{ if .Values.app.imageTagOverride }}{{ .Values.app.imageTagOverride }}{{ else }}{{ .Values.app.image.tag }}{{ end }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.app.port }}
          protocol: TCP
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.app.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.security.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.healthChecks.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.healthChecks.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }} 