apiVersion: v1
kind: Service
metadata:
  name: {{ include "k3s-app.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "k3s-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: TCP
    name: http
  selector:
    {{- include "k3s-app.selectorLabels" . | nindent 4 }} 