# Staging values for node-app
replicaCount: 2

image:
  repository: europe-west1-docker.pkg.dev/certain-mission-467310-u4/node-app-repo/node-app
  tag: "staging"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30000

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 150m
    memory: 192Mi

autoscaling:
  enabled: false

env:
  NODE_ENV: "staging"
  PORT: "8080"

livenessProbe:
  enabled: true
  path: /health
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /health
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3 