apiVersion: v1
kind: Config
clusters:
- name: readonly-cluster
  cluster:
    server: CLUSTER_SERVER_PLACEHOLDER
    certificate-authority-data: CLUSTER_CA_PLACEHOLDER
contexts:
- name: readonly-context
  context:
    cluster: readonly-cluster
    user: readonly-user
    namespace: default
current-context: readonly-context
users:
- name: readonly-user
  user:
    token: READONLY_TOKEN_PLACEHOLDER 